tasks:
  - init: |
      composer install
      composer update
      npm install
      npm update
    command: |
      echo 'start command if needed'

ports:
  # apache server
  - port: 80
    visibility: private
    onOpen: open-preview
  # mysql db
  - port: 3306
    visibility: private
    onOpen: ignore
  - port: 8080
    visibility: private
    onOpen: ignore
  # mysql vscode extension
  - port: 8828
    visibility: private
    onOpen: ignore

vscode:
  extensions:
    - cweijan.vscode-mysql-client2